# Generated by Django 4.1 on 2023-01-05 14:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0004_alter_book_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True)),
                ('expected_end_at', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 14, 44, 16, 465341, tzinfo=datetime.timezone.utc))),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
